-- ============================================================
-- NuraWell — user_insights semantic recall (Upstash only)
-- Migration: 000060_user_insights_pgvector.sql
--
-- אין pgvector ב-Supabase. חיפוש סמנטי לתובנות (recall_past_memory)
-- מתבצע ב-Upstash Vector — namespace `user-memory`, מזהה `insight:{uuid}`.
--
-- סביבה שהריצה גרסה קודמת של מיגרציה זו עם pgvector:
--   supabase/scripts/revert_000060_user_insights_pgvector.sql
-- תובנות קיימות לפני הסנכרון:
--   cd apps/web && npm run backfill:insight-vectors
-- ============================================================

-- no-op: שומר על רצף המיגרציות בלי ליצור עמודות/RPC וקטוריים
